### ISSUE TITLE
Delphi 10.3.3 & 10.4 not work on Linux64. On POSIX work only macOS64...

### ISSUE THREAD

**Issue by jonyrh** [TetrisSQC/SynapseTCP#2]
Hello!
I'm testing SynapseTCP on Linux64 (Ubuntu 16/18/20 x64) and macOS 10.5.4 x64. On Linux64 all not work, but on macOS64 all work fine!
Me need TSNMPSend (smtpsend.pas)- but not work on linux64 and with sudo.
And all network SynapseTCP function in Test app.

**Comment by donaldshimoda** [comment]
Exactly the same problem, It send data via udp but cant receive nothing. Same code work perfect on windows...
